### ISSUE TITLE
Update to WPILib 2024.3.1

### ISSUE THREAD

**Issue by jamesdooley4** [robototes/Crescendo2024#87]
Include yet more network tables performance improvements with Shuffleboard (among many other things)

**Comment by jamesdooley4** [comment]
Hrm. It's already done. I think I saw the revlib at 2024.2.1

**Comment by TAKBS2412** [comment]
> Hrm. It's already done. I think I saw the revlib at 2024.2.1

Yeah, this upgrade happened at Glacier Peak and probably got lost in the sea of commits we had going on. The only reason I knew about it was because I happened to see the commit when I was watching someone look at the git history. (In the future, probably best to avoid upgrades like that during competition, to avoid running into any breaking changes).

Of note, the latest version of REVLib is [2024.2.3](https://docs.revrobotics.com/ion-control-system/sw/revlib/changelog#version-2024.2.3), so would be good to update that (edit: see #88).
